# Generated by Django 5.1 on 2024-09-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('entry1', models.FloatField()),
                ('entry2', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profits', models.JSONField()),
                ('signal_type', models.CharField(max_length=10)),
                ('signal_strength', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
