# Generated by Django 5.1 on 2024-10-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_signal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signal',
        ),
    ]
